package br.com.vivovaloriza.dbmetricsmonitor.intelligence.enums;

public enum AlertCode {
    LOCK_BLOCKED_SESSION,
    LOCK_BLOCKING_SESSION,
    HIGH_CONNECTION_USAGE,
    IDLE_IN_TRANSACTION_DETECTED,
    LONG_RUNNING_QUERY,
    LOW_CACHE_HIT_RATIO,
    HIGH_CPU_USAGE,
    HIGH_MEMORY_USAGE,
    INCIDENT_RECURRENT_PATTERN,
    ANOMALY_CONNECTION_SPIKE,
    ANOMALY_LOCK_SPIKE
}
