package br.com.vivovaloriza.dbmetricsmonitor.intelligence.enums;

public enum PenaltyCode {
    BLOCKED_LOCKS,
    BLOCKING_LOCKS,
    IDLE_IN_TRANSACTION,
    IDLE_IN_TRANSACTION_CRITICAL,
    HIGH_CONNECTION_USAGE,
    CRITICAL_CONNECTION_USAGE,
    LONG_RUNNING_QUERY,
    CRITICAL_LONG_RUNNING_QUERY,
    LOW_CACHE_HIT_RATIO,
    CRITICAL_CACHE_HIT_RATIO,
    HIGH_CPU_USAGE,
    CRITICAL_CPU_USAGE,
    HIGH_MEMORY_USAGE,
    RECURRENT_INCIDENTS,
    RECURRENT_LOCK_INCIDENTS
}
